server:
  port: 20002
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

spring:
  application:
    name: gateway-coupon-calculation-serv
  sleuth:
    sampler:
      # 采样率的概率，100%采样
      probability: 1
      # 每秒采样数字最高为100
      rate: 1000
  zipkin:
    sender:
      type: rabbit
    #    base-url: http://localhost:9411/
    rabbitmq:
      addresses: 127.0.0.1:5672
      queue: zipkin
logging:
  level:
    com.broadview.coupon: debug

# 开启所有management端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

